OUTPUT_DIR: "model/20201206_imprv_X_dota"
INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST:  1024
  MAX_SIZE_TEST:  1024
  RANDOM_ROTATE_ON: True # (0, 90, 180, or 270)
  BRIGHTNESS: 0.
  CONTRAST: 0.
  SATURATION: 0.
  HUE: 0.
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    STRIDE_IN_1X1: False
    BACKBONE_OUT_CHANNELS: 256
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    # normalizing the regression targets with FPN strides
    NORM_REG_TARGETS: True
    # positioning centerness on the regress branch.
    # Please refer to https://github.com/tianzhi0549/FCOS/issues/89#issuecomment-516877042
    CENTERNESS_ON_REG: True
    # using center sampling and GIoU.
    # Please refer to https://github.com/yqyao/FCOS_PLUS
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
DATASETS:
  TRAIN: ("dota_trainval_cut", "dota_test_cut")
  TEST: ("dota_test_cut",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (38000, 46000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 8  #原设置12
  WARMUP_METHOD: "constant"
TEST:
  IMS_PER_BATCH: 12
#TEST:
#  BBOX_AUG:
#    ENABLED: False
#    H_FLIP: True
#    SCALES: (400, 500, 600, 700, 900, 1000, 1100, 1200)
#    MAX_SIZE: 2000
#    SCALE_H_FLIP: True
